namespace NexusForever.Script.Instance.Expedition.Gauntlet
{
    public enum PublicEventObjective
    {
        GetIntoAirlock               = 1818,
        FindOutWhatHappenedToYou     = 1819,
        TalkToPilotTaboro            = 1821,
        KillTheBashBrothers          = 1822,
        KillTheHandlerAndHisPets     = 1834,
        KillTheOpposingFactionsTeam  = 1835,
        ActivateSwitches             = 1837,
        GatherAtTheSwarmPit          = 1842,
        SurviveTheFirstArena         = 1854,
        EnterTheFactionFrictionArena = 1857,
        EnterTheMainEventArena       = 1858,
        EnterTheCharnelChamber       = 1859,
        KillTheRockstarYeti          = 1864,
        KillTheChampionator          = 1865,
        KillTheVoodooKin             = 1866,
        DefeatTheGoonSquad           = 1869,
        DefeatTheHandlerAndHisPets   = 1870,
        DefeatSliceAndDice           = 1871,
        DefeatPyroManiac             = 1872,
        DefeatShowtime               = 1873,
        DefeatTheShockKing           = 1874,
        SurviveTheMainEvent          = 1875,
        ClearTheSecondAndThirdArenas = 1896,
        TalkToJudgeKain              = 1914,
        TalkToAgentLex               = 1915,
        CurrentScoring               = 1942,
        SaveGauntletContestantsFromTheDarkspur = 1951,
        CollectGoldenSkulls          = 1957,
        SurviveTheSplorg             = 1967,
        CollectGauntletScoreTokens   = 1974,
        EnterTheChamberOfChoices     = 1977,
        EndorseAProduct              = 2001,
        CollectGauntletScoreTokens2  = 4670,
        DefeatBrickBraggor           = 4671
    }
}