namespace NexusForever.Script.Instance.Raid.GeneticArchives
{
    public enum PublicEventObjective
    {
        DefeatExperimentX89                = 410,
        DefeatPhageMaw                     = 411,
        DefeatKuralakTheDefiler            = 412,
        DefeatThePhagetechPrototypes       = 413,
        DefeatDreadphageOhmna              = 415,
        DefeatThePhagebornConvergence      = 416,
        GeneticCollection                  = 1970,
        NorthPowerCoreEnergy               = 2157,
        EastPowerCoreEnergy                = 2158,
        SouthPowerCoreEnergy               = 2159,
        WestPowerCoreEnergy                = 2160,
        PowerCycle                         = 2295,
        DefeatTheMalfunctioningBattery     = 2388,
        DefeatTheMalfunctioningPiston      = 2389,
        DefeatTheMalfunctioningDynamo      = 2390,
        DefeatTheMalfunctioningGear        = 2391,
        DefeatPhagetechGuardianC148        = 2393,
        DefeatPhagetechGuardianC432        = 2394,
        DefeatTheGeneticMonstrosity        = 2395,
        DefeatTheGravitronOperator         = 2396,
        DefeatTheHideouslyMalformedMutant  = 2397,
        DefeatTheFetidMiscreation          = 2433,
        DefeatTheCorruptedBeasts           = 2450,
        GetThroughTheArchiveDefenseSystem  = 2452,
        DefeatTheParagonsOfSymbiosis       = 2453,
        DefeatConstructsInTheCentrifuge    = 2454,
        DefeatEverythingInNaniteFilledRoom = 2455,
        WhoLetTheDogsOut                   = 2492,
        DeathFromAbove                     = 2493,
        AhThatsTheStuff                    = 2494,
        AloneInTheDark                     = 2495,
        VennDiagramOfPower                 = 2496,
        DeadlyDanceRevolution              = 2498,
        ClearTheAir                        = 2499,
        EventHorizon                       = 2500,
        PreemptiveStrike                   = 2501,
        PowerConservation                  = 2502,
        ImmortalExperimentX89              = 2572,
        ImmortalKuralakTheDefiler          = 2573,
        ImmortalPhageMaw                   = 2574,
        ImmortalPhagetechPrototypes        = 2575,
        ImmortalPhagebornConvergence       = 2576,
        ImmortalDreadphageOhmna            = 2577,
        PhagetechPhasedancer               = 2602,
        CutTheRedWire                      = 2603,
        ProductionHalted                   = 2604,
        MerelyThePrototype                 = 2605,
        ClearTheAir2                       = 2615,
        Skywalker                          = 2702,
        TotalPower                         = 4651
    }    
}