namespace NexusForever.Script.Instance.Expedition.FragmentZero
{
    public enum PublicEventObjective
    {
        SearchForMissingCrew                          = 4397,
        EliminateSkeech                               = 4416,
        DefeatProjectMatron                           = 4417,
        ReturnToTheAirlockOfTheBiomaticsChamber       = 4418,
        SearchInsideTheBiomaticsChamberForSyrus       = 4420,
        SearchInsideTheIncubationComplexForJo         = 4421,
        FollowTheFriendlySkeech                       = 4422,
        DefeatPrototypeAlphansideTheIncubationComplex = 4423,
        SearchJoInsideTheIncubationComplex            = 4424,
        SurviveTheSkeechAmbush                        = 4425,
        ContinueTheSearchForTheMissingCrew            = 4426,
        ReturnToTheAirlockOfTheIncubationComplex      = 4427,
        ContinueTheSearchForTheMissingCrewLifeOverseer= 4429,
        ContinueTheSearchForHugo                      = 4430,
        CollectCargoCrate                             = 4431,
        SearchCrewmateSyrusCorpse                     = 4432,
        SearchForHugo                                 = 4443,
        DefeatTheLifeOverseer                         = 4444,
        LocateHugo                                    = 4445,
        ReturnToTheAirlockOfTheLifeOverseersCreche    = 4446,
        StayCloseToHugo                               = 4447,
        DiscoverTheTwoLostRecordings                  = 4448,
        DefeatPrototypeBeta                           = 4449,
        DefeatPrototypeDelta                          = 4450,
        FindOhmnasHiddenRecording                     = 4454,
        FindLucentsHiddenRecording                    = 4455,
        EliminateTheHordesOfSkeechInfestingTheArea    = 4584,
        EliminateTheHordesOfSkeechInfestingTheArea2   = 4585,
        EliminateTheHordesOfSkeechInfestingTheArea3   = 4586,
        SmashXenobiteEggsInsideTheIncubationComplex   = 4632,
        DeactivateAutomatedDefences                   = 4635,
        SeeIfHugoHasAWayOutOfThisMess                 = 4641,
        SpeakWithHugo                                 = 4642,
        WaitForHugo                                   = 4655,
        CollectCargoCrate2                            = 4684,
        KillExperimentalSkeechOnFragmentZero          = 4686,
        GoldMedalTimer                                = 4690,
        LocateTheShipsBlackBox                        = 4693,
    }
}